export const THREE = () => import(/* webpackChunkName: "chunk-THREEComponent" */'./three')

export const THREEComponent = () => import(/* webpackChunkName: "chunk-THREEComponent" */'./base/threecomponent')
export const Stats = () => import(/* webpackChunkName: "chunk-THREEComponent" */'./base/stats')
export const OrbitControls = () => import(/* webpackChunkName: "chunk-THREEComponent" */'./base/orbitcontrols')
export const CSS2DRenderer = () => import(/* webpackChunkName: "chunk-THREEComponent" */'./base/css2drenderer')
export const CSS3DRenderer = () => import(/* webpackChunkName: "chunk-THREEComponent" */'./base/css3drenderer')
export const WebGLRenderer = () => import(/* webpackChunkName: "chunk-THREEComponent" */'./base/webglrenderer')
export const Raycaster = () => import(/* webpackChunkName: "chunk-THREEComponent" */'./base/raycaster')
export const MashBasicMaterial = () => import(/* webpackChunkName: "chunk-THREEComponent" */'./base/meshbasicmaterial')
export const Texture = () => import(/* webpackChunkName: "chunk-THREEComponent" */'./base/texture')

export const AnimatedPanorama = () => import(/* webpackChunkName: "chunk-THREEComponent" */'./prefabs/animatedpanorama')
export const Panorama = () => import(/* webpackChunkName: "chunk-THREEComponent" */'./prefabs/panorama')
export const Prebuild = () => import(/* webpackChunkName: "chunk-THREEComponent" */'./prefabs/mixin/prebuild')
export const AdMesh = () => import(/* webpackChunkName: "chunk-THREEComponent" */'./prefabs/admesh')
export const ProductMesh = () => import(/* webpackChunkName: "chunk-THREEComponent" */'./prefabs/productmesh')
export const HotspotMesh = () => import(/* webpackChunkName: "chunk-THREEComponent" */'./prefabs/hotspotmesh')
