export {default as ViewspotTools} from './viewspot'
export {default as AdvancedTools} from './advanced'
// export {default as AdspotTools} from './adspot'
// export {default as HotspotTools} from './hotspot'
// export {default as ProductspotTools} from './productspot'
export {default as SpotsTools} from './spots'
